-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.38-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for v-jet
CREATE DATABASE IF NOT EXISTS `v-jet` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `v-jet`;

-- Dumping structure for table v-jet.blog
CREATE TABLE IF NOT EXISTS `blog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` text,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `author_name` char(50) DEFAULT NULL,
  `name` varchar(250) DEFAULT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;

-- Dumping data for table v-jet.blog: ~21 rows (approximately)
/*!40000 ALTER TABLE `blog` DISABLE KEYS */;
INSERT INTO `blog` (`id`, `text`, `date`, `author_name`, `name`) VALUES
	(1, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n', '2019-08-09 00:00:00', 'bogdan', 'Interesting and long Name form first post'),
	(2, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-09 00:00:00', 'Bogdan', 'Interesting and long Name form this post'),
	(3, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'vasya', 'Interesting and long Name form third post'),
	(4, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'petya', 'Interesting and long Name form fourth post'),
	(5, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'olya', 'Interesting and long Name form fifth post'),
	(6, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'andrey', 'Just ussual post name'),
	(7, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'vasya', 'Just ussual post name'),
	(8, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'vasya', 'Just ussual post name'),
	(9, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'vasya', 'Just ussual post name'),
	(10, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'vasya', 'Just ussual post name'),
	(11, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'name', 'Just ussual post name'),
	(12, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'Bogdan', 'Just ussual post name'),
	(13, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'asd', 'Just ussual post name'),
	(14, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'asd', 'Just ussual post name'),
	(15, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'my name', 'Just ussual post name'),
	(16, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'my name', 'Just ussual post name'),
	(17, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-11 00:00:00', 'my name3', 'Just ussual post name'),
	(18, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '0000-00-00 00:00:00', NULL, 'Just ussual post name'),
	(19, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-12 22:41:17', 'author', 'Just ussual post name'),
	(20, 'Blog posts started to get more and more like articles. As a bazillion blogs crowded the Internet, the bar began to raise.\r\n Blog posts began to have more interviews. They presented interesting data. Posts got longer as bloggers sought to stand out and deliver more value, until 1,000 words has become fairly standard, and 2,000-word posts are not uncommon. SEO keywords? value lessened as Google cracked down on keyword-stuffed content. Also, as blogs got more professional, many hired editors.\r\n On the article-writing side, there was also movement. Many print magazines began posting copies of their articles online. Suddenly, magazine headlines needed to drive traffic, just like blog-post headlines, and headline styles evolved. They published more opinion-driven pieces from thought leaders. Some also put up blogs where they let writers hit the button on their own.\r\n Wordcounts shortened for print, as ad revenue migrated online. Some magazines went online-only. Their style got breezier and more casual.\r\n To sum up, the two types of writing began to merge into one. Definitions got squishy, and now there?s a lot of confusion.\r\n Except about one thing: Blog posts tend topay crap, and articles tend to pay better.', '2019-08-12 22:42:17', 'author', 'Just ussual post name'),
	(21, 'My last post before commit', '2019-08-13 09:58:31', 'Kirill', 'Final Post');
/*!40000 ALTER TABLE `blog` ENABLE KEYS */;

-- Dumping structure for table v-jet.comments
CREATE TABLE IF NOT EXISTS `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `blogID` int(11) DEFAULT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comment` text NOT NULL,
  `author_name` varchar(50) DEFAULT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;

-- Dumping data for table v-jet.comments: ~15 rows (approximately)
/*!40000 ALTER TABLE `comments` DISABLE KEYS */;
INSERT INTO `comments` (`id`, `blogID`, `time`, `comment`, `author_name`) VALUES
	(1, 1, '2019-08-10 18:49:20', 'some comment', 'Bogdan'),
	(2, 1, '2019-08-10 18:50:00', 'bla blabal', 'Bogdan'),
	(3, 1, '2019-08-10 18:52:19', 'ddsa', 'Bogdan'),
	(4, 2, '2019-08-10 18:54:37', 'i like this post. It\'s exactly what i\'m looked for', 'Bogdan'),
	(5, 2, '2019-08-10 18:55:04', 'i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for', 'Bogdan'),
	(6, 3, '2019-08-10 18:55:04', 'dddaaa ss', 'Bogdan'),
	(7, 4, '2019-08-10 18:55:04', 'dddaaa ss', 'Bogdan'),
	(8, 5, '2019-08-10 18:55:04', 'dddaaa ss', 'Bogdan'),
	(9, 6, '2019-08-10 18:55:04', 'dddaaa ss', 'Bogdan'),
	(10, 2, '2019-08-12 11:52:45', 'i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for', 'valisii utkin'),
	(11, 2, '2019-08-12 12:06:21', 'i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for i like this post. It\'s exactly what i\'m looked for', 'my name'),
	(12, 2, '2019-08-12 17:05:00', 'new comment for this greate post', 'bogdan'),
	(13, 2, '2019-08-12 17:05:59', 'Last test with comments, i hope so', 'bogdan'),
	(22, 5, '2019-08-10 18:55:04', 'dddaaa ss asdasd', 'Bogdan'),
	(23, 2, '2019-08-13 09:57:43', 'my last comment befor commit', 'Kirill');
/*!40000 ALTER TABLE `comments` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
